{
 "title": "TODO API - Observability",
 "description": "Desafio 6 alertas com grafana, prometheus, alert manager para discord.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU %",
   "type": "timeseries",
   "description": "Monitoramento para CPU da aplicação",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"todo-api\", __name__=\"process_cpu_seconds_total\"}"
    }
   ]
  },
  {
   "title": "Memória RAM",
   "type": "timeseries",
   "description": "Monitore a quantidade de memória RAM utilizada",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{job=\"todo-api\", __name__=\"process_resident_memory_bytes\"}"
    }
   ]
  },
  {
   "title": "Latência P95",
   "type": "timeseries",
   "description": "Monitoramento de latência",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(http_request_duration_seconds_bucket[5m])\n  )\n)"
    }
   ]
  },
  {
   "title": "Erros 5xx",
   "type": "timeseries",
   "description": "Monitoramento de erros 5xx",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{status_code=~\"5..\", __name__=\"http_requests_total\"}"
    }
   ]
  },
  {
   "title": "Requisições por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{__name__=\"http_requests_total\"}"
    }
   ]
  }
 ]
}