services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - internal-net

  frontend:
    build: ./frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: /api
    depends_on:
      db:
        condition: service_started
    networks:
      - internal-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend:
    build: ./backend
    environment:
      PORT: 3001
      DB_HOST: db
      DB_USER: mateus
      DB_PASS: mypassword
      DB_NAME: mydb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal-net

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - internal-net
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - db-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./backend/observability/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.path=/prometheus"
    depends_on:
      - backend
    networks:
      - internal-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - internal-net

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./backend/observability/alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      - internal-net
    depends_on:
      - discord-webhook-adapter

  discord-webhook-adapter:
    image: benjojo/alertmanager-discord:latest
    env_file:
      - .env
    ports:
      - "9094:9094"
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge

volumes:
  db-data:
  prometheus_data:
  grafana_data:
