apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack
    receivers:
      - uid: slack-receiver
        type: slack
        settings:
          url: "YOUR_WEBHOOK_URL"
          recipient: "#SLACK_CHANNEL_NAME"
