name: Deploy
on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION_NAME }}
  ECR_BACKEND: ${{ secrets.ECR_BACKEND_URL }}
  S3_FRONTEND: ${{ secrets.S3_FRONTEND_BUCKET }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build e push backend
        run: |
          docker build -t $ECR_BACKEND:latest -t $ECR_BACKEND:${{ github.sha }} ./backend
          docker push $ECR_BACKEND:latest
          docker push $ECR_BACKEND:${{ github.sha }}

      - name: Deploy backend no ECS
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.ECS_BACKEND_SERVICE_NAME}} \
            --force-new-deployment \
            --region ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Sync frontend para S3
        run: |
          aws s3 sync ./frontend/out s3://${{ env.S3_FRONTEND }} \
            --delete \
            --region ${{ env.AWS_REGION }}
